### PR TITLE
ci: add publish job

### PR DESCRIPTION
**Pull request by AdnoC**
<< Describe the changes >>

Closes issue:

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Follows the commit message policy, appropriate for next version
- [x] Has documentation updated, a DU ticket, or requires no documentation change
- [x] Includes new tests, or was unnecessary
- [x] Code is reviewed for security by: << Name here >>

### CODE REVIEW

**Comment by AdnoC** [comment]
The question is: do we still have the credentials we need to publish?

**Comment by stephenmathieson** [comment]
> do we still have the credentials we need to publish?

I have *my* account:

```xml
    <server>
      <id>ossrh</id>
      <username>stephendeque</username>
      <password>REDACTED</password>
    </server>
```

We should probably create one for CI tho. 🤔

**Comment by stephenmathieson** [comment]
Created a JIRA for the IHD folks: https://dequesrc.atlassian.net/browse/IHD-2522

**Comment by stephenmathieson** [comment]
We're now waiting on an ownership transfer: https://issues.sonatype.org/browse/OSSRH-56461

Once that issue is closed, we should be able to update the credentials here and start deploying from CI.

**Pull request merged**
