### PR TITLE
feat: preparation for aXe 3.0+ release

### PR DESCRIPTION
**Pull request by akornmeier**
- remove references to axe.a11yCheck
- bump versions of Selenium webdriver
- update axe version to 2.6.1 for tests in test/resources directory

### CODE REVIEW

**Comment by akornmeier** [comment]
Was updated, not added. The previous version was v2.0.5

**Comment by WilcoFiers** [comment]
Also, does this still work with shadow DOM selectors:

https://github.com/dequelabs/axe-selenium-java/blob/master/src/main/java/com/deque/axe/AXE.java#L154

**Comment by dylanb** [comment]
@WilcoFiers This is a 2.6 upgrade in prep for 3.0, the selector issue should be fixed once we do the actual upgrade - WDYT?

**Comment by WilcoFiers** [comment]
@dylanb This isn't an update to 2.6, people can already use 2.6 with this package. We need everything to be in a 3.0 prerelease state. That includes having tests we can run to verify it works with the changes in aXe 3.0.

**Comment by akornmeier** [comment]
@WilcoFiers - Added a shadow dom selector to the test page and verified the existing code works with shadow dom selectors. Once aXe 3.0 is added to the project we could add some tests that test shadow elements...

**Pull request merged**
